from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('',views.home,name="home"),
    path('home',views.home,name="home"),
    path('services',views.services,name="services"),
    path('contact',views.contact,name="contact"),
    path('testimonials',views.testimonials,name="testimonials"),
    path('about',views.about,name="about"),
    path('login',views.userlogin,name="login"),
    path('logout/', views.logout_view, name='logout'),

    # ADMIN
    path('adminpage',views.adminpage,name="adminpage"),
    path('AddPrincipal',views.AddPrincipal,name="AddPrincipal"),
    path('AdminAddHOD', views.AdminAddHOD, name='AdminAddHOD'),
    path('AdminViewStudents', views.AdminViewStudents, name='AdminViewStudents'),
    path('AdminViewFaculties', views.AdminViewFaculties, name='AdminViewFaculties'),
    path('AdminViewHODs', views.AdminViewHODs, name='AdminViewHODs'),
    path('AdminViewLeaveLetters', views.AdminViewLeaveLetters, name='AdminViewLeaveLetters'),
    path('AdminAttendance', views.AdminAttendance, name='AdminAttendance'),
    path('AdminAddFaculty/', views.AdminAddFaculty, name='AdminAddFaculty'),
    path('removePrincipal/<int:pk>/', views.removePrincipal, name='removePrincipal'),
    path('removeHod/<int:pk>/', views.removeHod, name='removeHod'),
    path('removeFaculty/<int:pk>/', views.removeFaculty, name='removeFaculty'),
    path('removeStudent/<int:pk>/', views.removeStudent, name='removeStudent'),
    path('ViewDepartments', views.ViewDepartments, name='ViewDepartments'),
    path('AdminAddDepartments', views.AdminAddDepartments, name='AdminAddDepartments'),
    path('ViewSemesters', views.ViewSemesters, name='ViewSemesters'),
    path('AdminAddSemesters', views.AdminAddSemesters, name='AdminAddSemesters'),
    path('AdminDeleteSem/<int:id>/', views.AdminDeleteSem, name='AdminDeleteSem'),
    path('AdminDeleteDepartments/<int:id>/', views.AdminDeleteDepartments, name='AdminDeleteDepartments'),
    

    # PRINCIPAL
    path('PrincipalDash',views.PrincipalDash,name="PrincipalDash"),
    path('PrincipalAddHod',views.PrincipalAddHod,name="PrincipalAddHod"),
    path('PrincipalAttendance',views.PrincipalAttendance,name="PrincipalAttendance"),
    path('PrincipalViewHod', views.PrincipalViewHod, name='PrincipalViewHod'),
    path('PrincipalViewFaculty', views.PrincipalViewFaculty, name='PrincipalViewFaculty'),
    path('PrincipalViewStudents', views.PrincipalViewStudents, name='PrincipalViewStudents'),
    path('PrincipalViewLeaveletters/', views.PrincipalViewLeaveletters, name='PrincipalViewLeaveletters'),
    path('approve_reject_leavePrincipal/<int:leave_id>/', views.approve_reject_leavePrincipal, name='approve_reject_leavePrincipal'),
    path('PrincipalEditProfile/<int:user_id>/', views.PrincipalEditProfile, name='PrincipalEditProfile'),
    path('PrincipalRemoveHod/<int:id>/', views.PrincipalRemoveHod, name='PrincipalRemoveHod'),

    # HOD
    path('HodDash',views.HodDash,name="HodDash"),
    path('HodAddFaculty',views.HodAddFaculty,name="HodAddFaculty"),
    path('HodViewFaculties',views.HodViewFaculties,name="HodViewFaculties"),
    path('deleteFaculty/<int:id>',views.deleteFaculty,name="deleteFaculty"),
    path('HodAttendance',views.HodAttendance,name="HodAttendance"),
    path('HodStudents',views.HodStudents,name="HodStudents"),
    path('HodNotes',views.HodNotes,name="HodNotes"),
    path('HodInternal',views.HodInternal,name="HodInternal"),
    path('HodLeave',views.HodLeave,name="HodLeave"),
    path('HodAddAttendance/', views.HodAddAttendance, name='HodAddAttendance'),
    path('HodViewAttendance/', views.HodViewAttendance, name='HodViewAttendance'),
    path('mark-attendance/<int:pk>/', views.MarkAttendanceFaculty, name='MarkAttendanceFaculty'),
    path('approve_reject_leaveHodFaculty/<int:leave_id>/', views.approve_reject_leaveHodFaculty, name='approve_reject_leaveHodFaculty'),
    path('approve_reject_leaveHodStudent/<int:leave_id>/', views.approve_reject_leaveHodStudent, name='approve_reject_leaveHodStudent'),
    path('HodViewLeaveletters/', views.HodViewLeaveletters, name='HodViewLeaveletters'),
    path('update-role/', views.update_role, name='update_role'),
    path('update-subjects/', views.update_subjects, name='update_subjects'),
    path('HodAddSubjects', views.HodAddSubjects, name='HodAddSubjects'),
    path('remove-subject/<int:subject_id>/', views.remove_subject, name='remove_subject'),
    path('HodDeleteSubjects/<int:id>/', views.HodDeleteSubjects, name='HodDeleteSubjects'),

    # FACULTY
    path('FacultyDash',views.FacultyDash,name="FacultyDash"),
    path('remove-student/<int:student_id>/', views.remove_student, name='remove_student'),
    path('faculty-attendance/', views.facultyAttendance, name='FacultyAttendance'),
    path('faculty-students/', views.FacultyStudents, name='FacultyStudents'),
    path('FacultyNotes',views.facultyNotes,name="FacultyNotes"),
    path('FacultyInternal',views.FacultyInternal,name="FacultyInternal"),
    path('FacultyLeave',views.FacultyLeave,name="FacultyLeave"),
    path('StdApproval<str:pk>',views.StdApproval,name="StdApproval"),
    path('ParentApproval<str:pk>',views.ParentApproval,name="ParentApproval"),
    path('StdApprove',views.StdApprove,name="StdApprove"),
    path('ParentApprove',views.ParentApprove,name="ParentApprove"),
    path('MarkAttendance/<int:pk>/',views.MarkAttendance,name="MarkAttendance"),
    path('MarkAttendanceAfternoon/<int:pk>/',views.MarkAttendanceAfternoon,name="MarkAttendanceAfternoon"),
    path('facultyAttendance/', views.facultyAttendance, name='facultyAttendance'),
    path('FacultyViewAttendance/', views.FacultyViewAttendance, name='FacultyViewAttendance'),
    path('facultyAssignments/', views.facultyAssignments, name='FacultyAssignments'),
    path('faculty_assignments/', views.faculty_view_assignments, name='faculty_view_assignments'),
    path('faculty_add_assignment', views.faculty_add_assignment, name='faculty_add_assignment'),
    path('faculty_view_assignments/', views.faculty_view_assignments, name='faculty_view_assignments'),
    path('delete_assignment/<int:assignment_id>/', views.delete_assignment, name='delete_assignment'),
    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
    path('add_notes/', views.add_notes, name='add_notes'),
    path('FacultyAddInternal', views.FacultyAddInternal, name='FacultyAddInternal'),
    path('edit_marks/<int:student_id>/', views.edit_marks, name='edit_marks'),
    path('promote-student/<int:student_id>/', views.promote_student, name='promote_student'),
    path('display-students/', views.display_students, name='display_students'),
    path('display-months/', views.display_months, name='display_months'),
    path('FacultyViewLeaveletters/', views.FacultyViewLeaveletters, name='FacultyViewLeaveletters'),
    path('approve_reject_leaveFaculty/<int:leave_id>/', views.approve_reject_leaveFaculty, name='approve_reject_leaveFaculty'),
    path('FacultyEditProfile/<int:faculty_id>/', views.FacultyEditProfile, name='FacultyEditProfile'),
    path('approve-or-reject-assignment/<int:assignment_id>/<str:action>/', views.approve_or_reject_assignment, name='approve_or_reject_assignment'),
    

    # STUDENT
    path('StudentReg',views.StudentReg,name="StudentReg"),
    path('studentDash',views.studentAttendance,name="studentDash"),
    path('studentAttendance',views.studentAttendance,name="studentAttendance"),
    path('studentStudents',views.studentStudents,name="studentStudents"),
    path('studentAssignments',views.studentAssignments,name="studentAssignments"),
    path('studentNotes',views.studentNotes,name="studentNotes"),
    path('studentInternal',views.studentInternal,name="studentInternal"),
    path('studentLeave',views.studentLeave,name="studentLeave"),
    path('submit_assignment/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('StudentEditProfile/<int:id>/', views.StudentEditProfile, name='StudentEditProfile'),
    path('DelStdLeave/<int:id>/', views.DelStdLeave, name='DelStdLeave'),
    path('ViewStudentProfile/<int:id>/', views.ViewStudentProfile, name='ViewStudentProfile'),
    
    # PARENT
    path('ParentReg',views.ParentReg,name="ParentReg"),
    path('ParentDash',views.ParentDash,name="ParentDash"),
    path('ParentAttendance', views.ParentAttendance, name='ParentAttendance'),
    path('ParentStudents',views.ParentStudents,name="ParentStudents"),
    path('ParentAssignments',views.ParentAssignments,name="ParentAssignments"),
    path('ParentNotes',views.ParentNotes,name="ParentNotes"),
    path('ParentInternal',views.ParentInternal,name="ParentInternal"),
    path('approve-reject-leave/<int:leave_id>/', views.approve_reject_leave, name='approve_reject_leave'),
    path('ParentLeaveLetter', views.ParentLeaveLetter, name='ParentLeaveLetter'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)