# Generated by Django 5.0.4 on 2024-04-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=500, null=True)),
                ('Max_Faculty', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Date', models.CharField(max_length=100, null=True)),
                ('Activity_Name', models.CharField(max_length=100, null=True)),
                ('Activity_Description', models.CharField(max_length=100, null=True)),
                ('Activity_images', models.FileField(null=True, upload_to='activity_Img')),
                ('Is_Active', models.CharField(default='Waiting', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Dob', models.CharField(max_length=100, null=True)),
                ('Faculty_Doj', models.CharField(max_length=100, null=True)),
                ('Faculty_Designation', models.CharField(max_length=100, null=True)),
                ('Faculty_PhoneNUm', models.IntegerField(null=True)),
                ('Faculty_Profile', models.FileField(null=True, upload_to='faculty_Img')),
                ('Is_Active', models.CharField(default='True', max_length=10)),
                ('role', models.CharField(max_length=100, null=True)),
                ('sem', models.CharField(max_length=100, null=True)),
                ('Faculty_Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acadamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalWorkingDays', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hod_Dob', models.CharField(max_length=100, null=True)),
                ('Hod_Doj', models.CharField(max_length=100, null=True)),
                ('Hod_Designation', models.CharField(max_length=100, null=True)),
                ('Hod_PhoneNUm', models.IntegerField(null=True)),
                ('Hod_Profile', models.FileField(null=True, upload_to='hod_Img')),
                ('Is_Active', models.CharField(default='True', max_length=10)),
                ('Hod_Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyLeaveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('isApproved', models.CharField(default='False', max_length=100, null=True)),
                ('leave_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('leave_Hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hod')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('count', models.IntegerField(null=True)),
                ('attendance_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('attendance_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hod')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_Dob', models.CharField(max_length=100, null=True)),
                ('principal_Doj', models.CharField(max_length=100, null=True)),
                ('principal_PhoneNUm', models.IntegerField(null=True)),
                ('principal_Profile', models.FileField(null=True, upload_to='principal_Img')),
                ('Is_Active', models.CharField(default='True', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HodLeaveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('isApproved', models.CharField(default='False', max_length=100, null=True)),
                ('leave_Hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hod')),
                ('leave_Principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.principal')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Notes', models.FileField(null=True, upload_to='faculty_notes')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('module', models.CharField(max_length=100, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('Semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_no', models.IntegerField(null=True)),
                ('date_of_submission', models.DateField(null=True)),
                ('assignment_question', models.CharField(max_length=100, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facultysubject')),
                ('Sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Dob', models.CharField(max_length=100, null=True)),
                ('AdmissionNo', models.CharField(max_length=100, null=True)),
                ('Student_yoj', models.CharField(max_length=100, null=True)),
                ('Student_Designation', models.CharField(max_length=100, null=True)),
                ('Student_PhoneNum', models.IntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('Student_Profile', models.FileField(null=True, upload_to='hod_Img')),
                ('Is_Active', models.CharField(default='Waiting', max_length=10, null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('attendance_status', models.CharField(default='Waiting', max_length=100, null=True)),
                ('attendance_statusAfternoon', models.CharField(default='Waiting', max_length=100, null=True)),
                ('Sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semesters')),
                ('Student_Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_Name', models.CharField(max_length=100, null=True)),
                ('Parent_num', models.CharField(max_length=100, null=True)),
                ('Parent_Profile', models.FileField(null=True, upload_to='hod_Img')),
                ('Is_Active', models.CharField(default='Waiting', max_length=10, null=True)),
                ('AdmissionNo', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stdParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(null=True)),
                ('answer', models.FileField(null=True, upload_to='hod_Img')),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facultyassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=10)),
                ('attendance_statusAfternoon', models.CharField(default='Waiting', max_length=100, null=True)),
                ('count', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, null=True)),
                ('nod', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('isApproved', models.CharField(default='False', max_length=100, null=True)),
                ('isApprovedFaculty', models.CharField(default='False', max_length=100, null=True)),
                ('isApprovedParent', models.CharField(default='False', max_length=100, null=True)),
                ('leave_Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parent')),
                ('leave_Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('leave_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departments')),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass1', models.IntegerField(null=True)),
                ('ass2', models.IntegerField(null=True)),
                ('ass3', models.IntegerField(null=True)),
                ('tp1', models.IntegerField(null=True)),
                ('tp2', models.IntegerField(null=True)),
                ('tp3', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('attendance_mark', models.IntegerField(null=True)),
                ('marks_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('marks_std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculties', to='app.subject'),
        ),
    ]
