# Generated by Django 5.0.4 on 2024-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dates',
            field=models.IntegerField(null=True),
        ),
    ]
